---
title: "AMPC18 Schedule"
author: ""
date: ""
output:
  pdf_document:
    keep_tex: true
  html_document:
    keep_md: true
    theme: "cerulean"
---

<style>
th, td {
    padding: 5px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>

\renewcommand{\arraystretch}{1.5}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library("gdata")
library("lubridate")
```

```{r readxls, echo=FALSE}
abstracts <- read.xls ("Maths Psych_V2.xlsx", sheet = 1, header = TRUE,
                              stringsAsFactors=FALSE)
titles <- read.xls ("Maths Psych_V2.xlsx", sheet = 3, header = TRUE,
                              stringsAsFactors=FALSE)
titles <- titles[titles$Title!="",]
titles$Title <- iconv(titles$Title)
titles$All.Authors <- iconv(titles$All.Authors)
titles$startt <- ""
```

```{r getTimes, echo=FALSE, warning=FALSE, results="asis"}

for (days in 1:2){
  for (mornaft in c("Morning", "Afternoon")){
    if (days==1){
      if (mornaft=="Morning"){
        thetime <- strptime("2018-02-14 09:00", format="%Y-%m-%d %H:%M", tz="")
        foct <- titles[titles$Sessions<3,]
      } else {
        foct <- titles[titles$Sessions<5 & titles$Sessions>2,]
      }
    } else if (days==2){
      if (mornaft=="Morning"){
        thetime <- strptime("2018-02-15 09:00", format="%Y-%m-%d %H:%M", tz="")
        foct <- titles[titles$Sessions>4 & titles$Sessions<7,]
      } else {
        foct <- titles[titles$Sessions>6,]
      }
    }
    
    if (mornaft=="Morning"){
      cat(paste("#", 
              weekdays(as.Date(thetime)), 
              as.Date(thetime, format="%d/%m/%Y"),"\n\n"))
    }
    
    for (tt in 1:dim(foct)[1]){
      foct$startt[tt] <- format(thetime, format="%H:%M")
      if (foct$Title[tt]=="**Coffee**"){
        thetime <- thetime + minutes(30)
      } else if (foct$Title[tt]=="Lunch"){
        thetime <- thetime + minutes(80)
      } else if (foct$Allocation[tt]=="B"){
        thetime <- thetime + minutes(10)
      } else if (foct$Allocation[tt]=="F"){
        thetime <- thetime + minutes(20)
      } else if (foct$Title[tt]=="Dinner"){
        thetime <- strptime("2018-02-15 18:00", format="%Y-%m-%d %H:%M", tz="")
        foct$startt[tt] <- format(thetime, format="%H:%M")
      } else {
        thetime <- thetime + minutes(1)
      }
    }
    
    
    kk <- dplyr::select(foct, c("startt","All.Authors","Title"))
    
    cat(paste("##", 
              mornaft,"\n\n"))
    
    print(knitr::kable(kk,
                       format='markdown',
                       col.names=c("Time","Authors","Title"),
                       row.names = FALSE,
                       escape=FALSE))
  
  }
}
```
